### ISSUE TITLE
Some improvemens in README

### ISSUE THREAD

**Issue by dai-shi** [bendrucker/angular-animate-change#2]
Hi, I like this small library pretty much. Here's my comment based on my experience when trying to use this library.

a) it needs to load angular-animete.js. Though it might be obvious to some experienced developers.

```
// node module exports the string 'animate-change' for convenience
angular.module('myApp', [
  require('angular-animate'),
  require('angular-animate-change')
]);
```

b) an example of how to write CSS. Might be common for angular experts, but class names flash-add and flash-add-active are not very ovbious. a demo page would also be nice.

**Comment by bendrucker** [comment]
Documenting the ngAnimate peer dep is totally reasonable. Done. Examples for people less familiar with ngAnimate would be great, but not something I'm willing to spend time on right now. Happy to review a PR if you want to try to create something.
