### ISSUE TITLE
Default config parameters

### ISSUE THREAD

**Issue by dai-shi** [bendrucker/angular-animate-change#3]
Currently, you need to specify both value and class like the following.

```
<div animate-change="value" change-class="class">
```

Would it be nice to have default config?
As for the class, the default is like "flash" as in the README.
For the value, is it possible to do like this

```
<div animate-change>{{some.obj.value}}</div>
```

and watch "some.obj.value"? It's one of typical usages.

Ideally, it would be wonderful if we can eliminate the number of watchers, I don't know if it is even possible.

Thanks.

**Comment by bendrucker** [comment]
> Would it be nice to have default config?

No, I don't see a good reason to do that. 

> For the value, is it possible to do like this...

Not really. It's technically possible to intercept and watch the interpolated value but I'm not willing to reverse engineer that deeply. There are curly brace bindings, ngBind, and all kinds of other things. 

Saving one watcher is not only impossible, but it's not going to have any impact on perf even if it were.
